name: Deploy

on:
  push:
    branches: [ "issue-4" ]
  pull_request:
    branches: [ "issue-4" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      working-directory: ./table-component
    - run: npm run build --if-present
      working-directory: ./table-component
    - run: mkdir gh-pages
    - run: touch gh-pages/.nojekyll
    - run: mv table-component/dist/* ./gh-pages/


    - name: Set up Python 3.
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies.
      run: |
        pip install -r requirements.txt

    - name: Get Data.
      run: |
        make

    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        branch: gh-pages
        force: true
        folder: gh-pages